cas-107 / 156 Increase time before proposals can start
DapperCollectives/CAST pull request #105
Opened 2022-07-06 14:20 UTC by rvmelkonian

In Production environment only we need to increase the time a proposal can go live to 1 hour after the current time for proposals. 

This should be reflected in the frontend UI and also validated on the backend as well. The reason for this change is because the snapshotter tool will need time to run and capture the chain so we know which accounts had the correct balance at the time the proposal was created:

• Adds SetStatus method on `createProposal` and `getProposal` controllers
• Checks if grace period has passed, only if strategy has a contract and environment is prod. Grace period is one hour

2022-07-06 21:54 UTC, jacksonConrad requested changes
I think I would take a different approach here.   I think its cleaner to ditch `SetStatus` completely.

We have `computedStatus` that is being set in the getProposal functions -- this feels like it belongs there, since it is basically part of that same set of conditional logic.  You could basically just do:

```
if p.computedStatus == `active` && p.contractName != nil && !time.Now().After(p.createdAt) {
    p.computedStatus = 'pending'
}
```

Although.... honestly the best way to do this might just to enforce it in the createProposal controller:
```
// assert that
p.Start_time >= time.Now().Add(time.Minute * 60)
```
That runs into the issue where if a user selects an hour in the future, time will go by before they click "submit" and this condition will fail.

Sooo maybe the best option is actually to add this logic in `createProposal`:
```
if p.contractName != nil && p.Start_time.Before(time.Now.Add(time.Hour)) {
  p.startTime = time.Now.Add(time.Hour)
}
```

2022-07-08 12:18 UTC, rvmelkonian commented
ok, updated.

2022-07-11 17:42 UTC, rvmelkonian commented on backend/main/server/app.go
> +	}
just added an environment variable check before this

2022-07-11 19:16 UTC, rvmelkonian commented on backend/main/server/app.go
> +	if os.Getenv("APP_ENV") != "PRODUCTION" {
my bad! that's fixed

2022-07-11 22:29 UTC, dbslone approved these changes
LGTM just need @jacksonConrad to review

2022-07-12 16:08 UTC, jacksonConrad approved these changes

2022-07-12 23:23 UTC, merged