Rich/cas 217 fix snapshot balance vote in `createVoteForProposal` controller
DapperCollectives/CAST pull request #135
Opened 2022-07-12 20:23 UTC by rvmelkonian

This is a subticket of cas-216. Some logic was missing in the Strategy `FetchBalance` method. Also now dummy balance data is returned for local dev.

2022-07-13 07:48 UTC, dbslone commented
We will forget in the future why there is fragmentation in the code. Can you write a quick doc in `docs/<filename>.md` that explains how this operates? Doesn't need to be detailed just need a quick high level explanation for now.

2022-07-13 13:39 UTC, germanurrus commented
I tested locally with FE creating and voting a proposal with `token-weighted-default` and works fine

2022-07-13 16:18 UTC, jacksonConrad requested changes

2022-07-13 16:18 UTC, jacksonConrad commented on backend/main/shared/snapshot-flow.go
> +type Balance struct {
Yeah probably cleanest to move this to `shared/structs.go` and use it in `balance.go` and `snapshot-flow.go` if that works

2022-07-13 16:18 UTC, jacksonConrad commented on backend/main/server/app.go
> +	if os.Getenv("APP_ENV") != "DEV" {
is this just to make testing locally easier?

2022-07-18 00:15 UTC, rvmelkonian commented
clsoing this as it was merged into `cas-172` which has now been merged to main.

2022-07-18 00:15 UTC, closed without merging