CAS-207: Update GetUserCommunities to return single community with multiple roles
DapperCollectives/CAST pull request #171
Opened 2022-07-15 21:19 UTC by jbluks

Ticket: [CAS-207](https://linear.app/dappercollectives/issue/CAS-207/update-backend-to-not-create-duplicate-user-records)

**Description:**

Backend call was returning duplicate communities for user with multiple roles in the community. Updated query to combine roles into array for single community.

2022-07-15 22:38 UTC, germanurrus requested changes

2022-07-15 22:38 UTC, germanurrus commented on backend/main/models/community_users.go
> +	Roles []string `json:"roles" validate:"required"`
Can we make it return `roles:` instead of `Roles` to keep it the same with the other fields the frontend is getting as response?

2022-07-15 22:42 UTC, germanurrus commented
@jbluks could you also update this function https://github.com/DapperCollectives/CAST/blob/main/frontend/packages/client/src/hooks/useUserRoleOnCommunity.js#L46

to use this code:
```
  const rolesInCommunity =
    communityUser
      ?.find((datum) => {
        return datum.id.toString() === communityId.toString();
      })
      ?.roles?.split(',') ?? [];
```
so the FE can split the roles string, this would be the only thing required to make this backend change to work.

2022-07-18 22:56 UTC, germanurrus approved these changes
Frontend code looks good!

2022-07-19 17:17 UTC, rvmelkonian commented
looks good !

2022-07-19 17:17 UTC, merged