cas-291 setup dev wallet with NFT tokens
DapperCollectives/CAST pull request #193
Opened 2022-07-20 12:59 UTC by rvmelkonian

This PR allows the dev wallet to own an NFT of `ExampleNFT.cdc`, this should enable smoke testing `balance-of`nfts` strategy in staging. 
* updates makeFile
* updates flow.json

N.B there is a failing test on this PR but the same test is failing on main. After that's resolved I'll pull updates from main.

2022-07-21 16:47 UTC, jacksonConrad commented on backend/Makefile
> -	migrate -path ./migrations -database "postgres://postgres:admin@localhost:5432/flow_snapshot?sslmode=disable" -verbose up
did you mean to delete `migrateup`? :)

2022-07-21 16:48 UTC, rvmelkonian commented on backend/Makefile
> -	migrate -path ./migrations -database "postgres://postgres:admin@localhost:5432/flow_snapshot?sslmode=disable" -verbose up
haha nop! will add in now

2022-07-21 16:49 UTC, jacksonConrad commented on backend/main/server/app.go
> -	if err := a.FlowAdapter.UserTransactionValidate(v.Addr, v.Message, v.Composite_signatures, v.TransactionId, a.TxOptionsAddresses, p.Choices); err != nil {
we will want to resolve the issue here before merging because otherwise Ledger wallets won't be validating properly

2022-07-21 16:51 UTC, jacksonConrad requested changes
just need to get the UserTransactionValidate function working again.  The package upgrade broke this because the `jsoncdc.Validate` function is expecting an additional arg.

2022-07-21 16:56 UTC, rvmelkonian commented
sweet. working on it.

2022-07-22 03:10 UTC, jacksonConrad approved these changes

2022-07-22 06:18 UTC, merged