CAS-403 - Update Community-Category options text
DapperCollectives/CAST pull request #361
Opened 2022-08-12 14:25 UTC by germanurrus

2022-08-15 17:50 UTC, jbluks approved these changes

2022-08-15 21:49 UTC, dbslone requested changes
@germanurrus lets remove the migration files since they are empty

2022-08-15 22:40 UTC, germanurrus commented
> @germanurrus lets remove the migration files since they are empty

I wasn't sure if we were going to need them since the original request was to change the categories to:

```
X  NFT Community => => should we create this one?  
✅ Social Community
✅ Creator Community 
X  Collector Community => should this one update service?  
✅ Protocol Community 
```

The ones with the green checkbox are already existing in the db but `NFT` and `Collector` are not. Also DAO and Service are not existing in the request CAS-403. Should we create `NFT` and `Collector and keep `DAO` and `Service`? @dbslone

2022-08-17 15:01 UTC, germanurrus commented on backend/migrations/000034_update_community_catergory.down.sql
> +COMMIT;
NFT is not being removed from the `community_type` I think it's not necessary to address that in the enum type

2022-08-24 18:41 UTC, germanurrus commented
@dbslone @jbluks did an update on migration file name

2022-08-24 21:56 UTC, jbluks approved these changes
LGTM

2022-08-25 13:35 UTC, rvmelkonian approved these changes
looks good and tested on my side.

2022-08-25 14:10 UTC, merged