cas -541: update search endpoint WIP
DapperCollectives/CAST pull request #546
Opened 2022-09-28 16:38 UTC by rvmelkonian

•adds method `appendFiltersToResponse`
•adds necessary fields onto search response

2022-10-03 03:59 UTC, germanurrus commented
It looks like the default search is not filtering correctly:

The URL is: 
http://localhost:5001/communities/search/defaultFeatured?start=0&count=10
The expected `defaultFeatured` should make filters to return only filters for the feature ones, also the all filter is gone.
I only have one feature community then dao should be 1 and the all filter should exist with one
Also when sending a filter that has 0 the result is the same, and the response brings the one feature community. 
(Note: I've added a category to the Flow community manually and it's dao and also I have created a second community using dao)
{
    "filters": [
        {
            "text": "dao",
            "amount": 2
        },
        {
            "text": "social",
            "amount": 0
        },
        {
            "text": "protocol",
            "amount": 0
        },
        {
            "text": "creator",
            "amount": 0
        },
        {
            "text": "nft",
            "amount": 0
        },
        {
            "text": "collector",
            "amount": 0
        }
    ],
    "results": {
        "data": [
            {
                "id": 1,
                "name": "Flow",
                "category": "dao",
                "categoryCount": 2,
                "body": "Vote on Flow Validators",
                "timestamp": "",
                "compositeSignatures": null,
                "creatorAddr": ""
            }
        ],
        "start": 0,
        "count": 1,
        "totalRecords": 1,
        "next": -1
    }
}

2022-10-03 04:23 UTC, germanurrus commented
also when sending text with space the front gets a 404:
<img width="818" alt="Screen Shot 2022-10-03 at 01 22 21" src="https://user-images.githubusercontent.com/7526740/193501233-3294043f-ca16-432d-a0cb-95ae0e357bc3.png">

2022-10-03 12:14 UTC, rvmelkonian commented
I've adjusted the SQL; 
now when I do
`http://localhost:5001/communities/search/defaultFeatured?start=0&count=10`

I get :
```
{
    "filters": [
        {
            "text": "dao",
            "amount": 0
        },
        {
            "text": "social",
            "amount": 0
        },
        {
            "text": "protocol",
            "amount": 0
        },
        {
            "text": "creator",
            "amount": 1
        },
        {
            "text": "nft",
            "amount": 0
        },
        {
            "text": "collector",
            "amount": 0
        }
    ],
    "results": {
        "data": [
            {
                "id": 114,
                "name": "rich",
                "category": "creator",
                "categoryCount": 1,
                "body": "<html>something</html>",
                "timestamp": "",
                "compositeSignatures": null,
                "creatorAddr": ""
            }
        ],
        "start": 0,
        "count": 1,
        "totalRecords": 1,
        "next": -1
    }
}
```

Adding `all` field now, it was never on the original response; adding it now. Special characters I am blocked on due to known issue with `mux` library. I've tried various solutions suggested on their issues page but none have worked so for.

2022-10-03 15:55 UTC, germanurrus commented
> The `all` field has been added
> 
> I've adjusted the SQL; now when I do `http://localhost:5001/communities/search/defaultFeatured?start=0&count=10`
> 
> I get :
> 
> ```
> {
>     "filters": [
>         {
>             "text": "dao",
>             "amount": 0
>         },
>         {
>             "text": "social",
>             "amount": 0
>         },
>         {
>             "text": "protocol",
>             "amount": 0
>         },
>         {
>             "text": "creator",
>             "amount": 1
>         },
>         {
>             "text": "nft",
>             "amount": 0
>         },
>         {
>             "text": "collector",
>             "amount": 0
>         },
>        {
>             "text": "all",
>             "amount":  1
>         }
>     ],
>     "results": {
>         "data": [
>             {
>                 "id": 114,
>                 "name": "rich",
>                 "category": "creator",
>                 "categoryCount": 1,
>                 "body": "<html>something</html>",
>                 "timestamp": "",
>                 "compositeSignatures": null,
>                 "creatorAddr": ""
>             }
>         ],
>         "start": 0,
>         "count": 1,
>         "totalRecords": 1,
>         "next": -1
>     }
> }
> ```
> 
> URL encoded Special characters I am blocked on due to known [issue](https://github.com/gorilla/mux/issues/77) with `mux` library. I've tried various solutions suggested on their issues page but none have worked so for.

For some reason this is not working on my side, I still get the same filters are before.

Just for clarification, then the `defaultFeatured` is sent as query search param, the frontend is expecting filters to be populated with the amount calculated based the featured communities returned.
When a text search is entered, filters should adjust on the result based on the search test. 

The `All` filter is always present, with the total amount of communities returned based on the search text or the defaultFeatured. 
When a filter is pressed, results changes but filters are the same and are kept based on the search text

2022-10-03 18:39 UTC, rvmelkonian commented
I just pushed again and I think there was one change not pushed to the branch; could you try pulling again? 

I just tested again and it seems to be working as expected with `all` filter always present, no duplicate `dao` filter counts etc. `defaultFeatured` only returns communities with `is_featured` column set to true. 

I just did `http://localhost:5001/communities/search/defaultFeatured?start=0&count=10`

and get returned 
```
{
    "filters": [
        {
            "text": "dao",
            "amount": 0
        },
        {
            "text": "social",
            "amount": 0
        },
        {
            "text": "protocol",
            "amount": 0
        },
        {
            "text": "creator",
            "amount": 2
        },
        {
            "text": "nft",
            "amount": 0
        },
        {
            "text": "collector",
            "amount": 0
        },
        {
            "text": "all",
            "amount": 2
        }
    ],
    "results": {
        "data": [
            {
                "id": 114,
                "name": "rich",
                "category": "creator",
                "categoryCount": 2,
                "body": "<html>something</html>",
                "timestamp": "",
                "compositeSignatures": null,
                "creatorAddr": ""
            },
            {
                "id": 115,
                "name": "rich",
                "category": "creator",
                "categoryCount": 2,
                "body": "<html>something</html>",
                "timestamp": "",
                "compositeSignatures": null,
                "creatorAddr": ""
            }
        ],
        "start": 0,
        "count": 2,
        "totalRecords": 2,
        "next": -1
    }
}
```

2022-10-03 22:24 UTC, germanurrus commented
- Filters for featured communities are not working, and filtering returns the same result for feature communities:
<img width="1471" alt="Screen Shot 2022-10-03 at 19 05 17" src="https://user-images.githubusercontent.com/7526740/193696095-5ebfdc82-edee-4c02-8e20-b7a7fd681a10.png">
In the image above, there should not be any results since I'm selecting a pill with no results (maybe if the pill is 0 make it not clickable) but still the backend should return 0 results

- When entering text with spaces, the url is not found and we get a 404 as a response:  
<img width="818" alt="Screen Shot 2022-10-03 at 01 22 21" src="https://user-images.githubusercontent.com/7526740/193696323-3a632f76-0d51-4ecc-845e-4b87be97abd5.png">


- Filters are not working on when results are returned on search, in the example below we should see only one result: 
<img width="1504" alt="Screen Shot 2022-10-03 at 19 23 53" src="https://user-images.githubusercontent.com/7526740/193696667-cd855811-a98c-4a69-88b6-c794f4f56119.png">

2022-10-03 22:25 UTC, germanurrus requested changes
Make comments about three bugs found on filtering

2022-10-05 17:25 UTC, jbluks commented
This PR will now be handled by this: https://github.com/DapperCollectives/CAST/pull/574

2022-10-05 17:25 UTC, closed without merging